### ISSUE TITLE
RSS周りでエラーになる

### ISSUE THREAD

**Issue by massongit** [dev-hato/youtube_streaming_watcher#154]
エラーハンドリングがうまくいってないっぽいです。

```
INFO	get feed:  https://www.youtube.com/feeds/videos.xml?channel_id=...
...
ERROR	Invoke Error 	{
    "errorType": "Error",
    "errorMessage": "Status code 404",
    "stack": [
        "Error: Status code 404",
        "    at ClientRequest.<anonymous> (/var/task/index.js:13:3005)",
        "    at Object.onceWrapper (events.js:520:26)",
        "    at ClientRequest.emit (events.js:400:28)",
        "    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)",
        "    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)",
        "    at HTTPParser.execute (<anonymous>)",
        "    at TLSSocket.socketOnData (_http_client.js:515:22)",
        "    at TLSSocket.emit (events.js:400:28)",
        "    at addChunk (internal/streams/readable.js:293:12)",
        "    at readableAddChunk (internal/streams/readable.js:267:9)"
    ]
}
```

**Comment by massongit** [comment]
一時的に404になるケースもあるようなので、404が一定以上続いたらチャンネル一覧から削除するとかが良さそうか？

**Comment by massongit** [comment]
チャンネルURL自体は生きている状態でRSSが404になる場合、少し経ってから再度RSSにアクセスすると200になるようだ。
